spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/icatch
    url: jdbc:mysql://localhost:3306/db25104?serverTimezone=Asia/Seoul
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbid251 #dbid251 #root
    password: dbpass251 #dbpass251  #chltjfbs23!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          characterEncoding: utf8
          charSet: utf8
          useUnicode: true

    # 정적 리소스 설정
    web:
      resources:
        static-locations: classpath:/static/
        add-mappings: true

    mvc:
      static-path-pattern: /**
      throw-exception-if-no-handler-found: true

    sql:
      init:
        mode: always

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

app:
  upload:
    dir: /home/t25104/uploads/

security:
  jwt:
    token:
      secret-key: a37sdl28ydh38gsl39syw72jsk10pq59abcdefghijklmnopqrstuvwxyz123456789
      expire-length: 259200000

logging:
  level:
    org.springframework.security: DEBUG
    org.example.icatch: DEBUG
    org.springframework.web: DEBUG

server:
  address: 0.0.0.0
  port: 60004
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-stacktrace: ALWAYS    # 스택 트레이스를 응답에 포함
    include-message: always